posts/urls.py
from django.urls import path
from . import views
app_name='posts'

urlpatterns = [
	path('', views. post_comment_create_and_list_view,  name='main-post-view'),
	path('liked/', views.like_unlike_post, name='like-post-view'),
	path('<pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
	path('<pk>/update', views.PostUpdateView.as_view(), name='post-update')


]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
	path('',views.ProfileListView.as_view(), name='all-profiles-view'),
	path('myprofile/', views.my_profile_view, name='my-profile-view'),
	path('my-invites/', views.invites_receved_view, name='my-invites-view'),
	path('to-invite/', views.invite_profiles_list_view, name='to-invite-profiles'),
	path('send-invatation', views.send_invatation, name='send_inva'),
	path('remove-friends', views.remove_from_friends, name='remove-friends'),
	path('<slug>/', views.ProfileDetailView.as_view(), name='profile-detail-view'),
	path('my-invites/accept/', views.accept_invatation, name='accept-invite'),
	path('my-invites/reject/', views.reject_invatation, name='reject-invite'),
]

snp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home


# from django.conf.urls import url
from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', home, name='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/main/home.html
{% extends 'base.html' %}

 {% block title %} Home{% endblock title %}

{% block content %}
		<div class="ui warning message">
		  <i class="close icon"></i>
		  <div class="header">
	    		The site is currently being repaired
	  		</div>
	  			if there are interruptions, please let us know
			</div>

		<h1>Welcome to SoBook </h1>
    	<h5>Here you can post with your friend you can send follow </h5>
    	<br>
    	<strong>Just enjoy!</strong>

    	<br>
    	<br>
{% endblock content %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'profiles:main-post-view' as path_to_posts %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:to-invite-profiles' as path_to_invites_profiles %}






<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{ path_to_home }}" class="{% if request.path == path_to_home %}active{%endif%}  item ">
        <h3>SoBook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:main-post-view' %}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles<!-- &nbsp; <div class="ui  red horizontal label ">{{ profile }}</div> -->
                    </a>
                    <a href="{{ path_to_invites_profiles }}" class="{% if request.path == path_to_invites_profiles %} active {% endif %} item ">
                        Send Invites
                    </a>
                    <a href="{{ path_to_my_invites }}" class="{% if request.path == path_to_my_invites %} active {% endif %} item">
                        Received Invites &nbsp; <div class="ui  red horizontal label ">{{ invite_num }}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{ path_to_my_profile }}" class="{% if request.path == path_to_my_profile %} active {% endif %}  item">
                <img src="{{picture.url}}" class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}"  class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
            <a href="{% url 'account_signup' %}"  class="ui item">
                Singup
            </a>
        {% endif %}
    </div>
  </div>
</div>